### ISSUE TITLE
Allow setting metrc type

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-lambda-python#245]
Looks like currently you can only submit a distribution. Would be nice if we could set the metric type like we can for Datadog integrations. 

```
lambda_stats.distribution(metric_name, value, tags=tags, timestamp=timestamp)

**Comment by agocs** [comment]
Alas! This is intentional. In a serverful environment, DogStatsD aggregates traditional metrics such as histograms, counters, etc and flushes the results to the metrics endpoint ever 10 seconds. In the lambda environment, we don't have an agent to do that for us, and we can have the same lambda function running several times concurrently, as the same "host". When the metrics endpoint sees traditional metrics being re-submitted from the same host, it overwrites old values with updated values. Distribution metrics don't have this behavior, and therefore they're the only metrics that can be submitted from a Lambda function.

This is hinted at in the docs [here](https://docs.datadoghq.com/metrics/types/?tab=count#:~:text=The%20Agent%20combines,stored%20as%2Dis.).

**Comment by djtecha** [comment]
Fascinating! Thank you for the quick response :)
