### ISSUE TITLE
ddtrace adding cmake as dependency balloons package size

### ISSUE THREAD

**Issue by devinmatte** [DataDog/datadog-lambda-python#349]
Recently it seems that `ddtrace` added `cmake` as a dependency, which has now ballooned the uncompressed size of the `datadog_lambda` package by `71 mb` requiring us to pin back to `1.15.0` to avoid adding hitting our lambda code size limit

It would be great if we didn't have to pin to an older version and the library could either pin or vendor a slimmed version of ddtrace (or something to avoid the package ballooning past a usable lambda size)

**Comment by duncanista** [comment]
https://github.com/DataDog/dd-trace-py/pull/6468 for visibility

**Comment by duncanista** [comment]
https://github.com/DataDog/datadog-lambda-python/pull/356 for visibility

**Comment by astuyve** [comment]
This should be fixed in ddtrace 1.17, however we'll be sticking with 1.15.x in this library for the next release due to an additional size increase in an unrelated part of the tracer, until at least we can verify that change is an absolute requirement.

Either way, I'll close this issue as I think the main issue is related to dd-trace.

Thanks!!
